#pragma kernel Postprocess

// 
// Postprocessor (tensor to vertex list conversion)
//

// Input
Texture2D<float> _Tensor;

// Output
RWBuffer<float4> _Vertices;

[numthreads(52, 1, 1)]
void Postprocess(uint id : SV_DispatchThreadID)
{
    uint offs = id * 3;

    float x =     _Tensor[uint2(0, offs + 2)] / 192;
    float y = 1 - _Tensor[uint2(0, offs + 1)] / 192;
    float z =     _Tensor[uint2(0, offs + 0)];

    _Vertices[id] = float4(x, y, z, 1);
}
